#!/usr/bin/env sh

# BOOTDSK=$(df / | grep / | cut -d" " -f1 | cut -d"s" -f 1,2)
# EFIPATH=$BOOTDSK"s1"

EFIPATH=$(diskutil list | grep -i "EFI" | awk '/ / {print $6}' | grep -m1 "disk")

sudo diskutil mount $EFIPATH
